### ISSUE TITLE
'hub' is not definded 

### ISSUE THREAD

**Issue by AselToktogulova** [vector-ai/vectorhub#68]
hello community, 

I got this error 

```
>>> from vectorhub.encoders.image.tfhub import BitSmall2Vec
>>> model=BitSmall2Vec()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ivaadmin/anaconda3/envs/x2vec/lib/python3.9/site-packages/vectorhub/encoders/image/tfhub/bit.py", line 27, in __init__
    self.init(model_url)
  File "/home/ivaadmin/anaconda3/envs/x2vec/lib/python3.9/site-packages/vectorhub/encoders/image/tfhub/bit.py", line 34, in init
    self.model = hub.load(self.model_url)
NameError: name 'hub' is not defined
```

what is missing?

**Comment by JackyKoh** [comment]
when installing did you run
``` 
pip install vectorhub
```
or 
```
pip install vectorhub[encoders-image-tfhub]
```

**Comment by AselToktogulova** [comment]
thanks, maybe also pip install --upgrade tensorflow_hub
